import {
  Controller, Get, Post, Patch, Delete,
  Body, Param, Query, ParseIntPipe, UseGuards, Req, ForbiddenException,
} from '@nestjs/common';
import { AuthGuard } from '@nestjs/passport';
import { InvoicesService } from './invoices.service';
import { CreateInvoiceDto } from './dto/create-invoice.dto';
import { UpdateInvoiceDto } from './dto/update-invoice.dto';
import { CreatePaymentDto } from './dto/create-payment.dto';
import { InvoiceStatus, InvoiceType } from '@prisma/client';
import { Roles } from '../common/decorators/roles.decorator';
import { RolesGuard } from '../common/guards/roles.guard';

@Controller('invoices')
@UseGuards(AuthGuard('jwt'))
export class InvoicesController {
  constructor(private invoicesService: InvoicesService) {}

  // ── Eligible items + auto-generate (must be before :id routes) ──────────────

  @Get('eligible/:projectId')
  getEligibleItems(
    @Param('projectId', ParseIntPipe) projectId: number,
    @Req() req: any,
  ) {
    const vendorId = req.user.vendor?.id;
    if (!vendorId) throw new ForbiddenException('Only vendor users can access this endpoint');
    return this.invoicesService.getEligibleItems(projectId, vendorId);
  }

  @Post('auto-generate')
  autoGenerateDraft(
    @Body('projectId') projectId: number,
    @Req() req: any,
  ) {
    const vendorId = req.user.vendor?.id;
    if (!vendorId) throw new ForbiddenException('Only vendor users can access this endpoint');
    return this.invoicesService.autoGenerateDraft(projectId, vendorId, req.user.id);
  }

  // ── Financials aggregate (PM / AM / Admin) ───────────────────────────────────

  @Get('financials')
  @UseGuards(RolesGuard)
  @Roles('SUPER_ADMIN', 'ADMIN', 'ACCOUNT_MANAGER', 'PROJECT_MANAGER')
  getFinancials(
    @Query('projectId') projectId?: string,
    @Query('vendorId')  vendorId?:  string,
    @Query('clientId')  clientId?:  string,
  ) {
    return this.invoicesService.getFinancials({
      projectId: projectId ? Number(projectId) : undefined,
      vendorId:  vendorId  ? Number(vendorId)  : undefined,
      clientId:  clientId  ? Number(clientId)  : undefined,
    });
  }

  // ── CRUD ─────────────────────────────────────────────────────────────────────

  @Get()
  findAll(
    @Req() req: any,
    @Query('clientId')    clientId?:    string,
    @Query('projectId')   projectId?:   string,
    @Query('vendorId')    vendorId?:    string,
    @Query('status')      status?:      InvoiceStatus,
    @Query('invoiceType') invoiceType?: InvoiceType,
  ) {
    const roles: string[] = req.user.roles ?? [];

    // CLIENT users can only see SENT+ invoices for their own company — enforce server-side
    const CLIENT_VISIBLE_STATUSES: InvoiceStatus[] = ['SENT', 'APPROVED', 'PAID', 'OVERDUE'];
    if (roles.includes('CLIENT')) {
      const scopedClientId = req.user.client?.id;
      if (!scopedClientId) return [];
      const safeStatus = status && CLIENT_VISIBLE_STATUSES.includes(status) ? status : undefined;
      return this.invoicesService.findAll({
        clientId:        scopedClientId,
        invoiceType:     'CLIENT',
        projectId:       projectId ? Number(projectId) : undefined,
        status:          safeStatus,
        excludeStatuses: ['DRAFT'],
      });
    }

    // VENDOR users can only see their own vendor invoices
    if (roles.includes('VENDOR_CONTACT') || roles.includes('CONTRACTOR')) {
      const scopedVendorId = req.user.vendor?.id;
      if (!scopedVendorId) return [];
      return this.invoicesService.findAll({
        vendorId:    scopedVendorId,
        invoiceType: 'VENDOR',
        projectId:   projectId ? Number(projectId) : undefined,
        status,
      });
    }

    return this.invoicesService.findAll({
      clientId:    clientId    ? Number(clientId)    : undefined,
      projectId:   projectId   ? Number(projectId)   : undefined,
      vendorId:    vendorId    ? Number(vendorId)     : undefined,
      status,
      invoiceType,
    });
  }

  @Get(':id')
  findOne(@Param('id', ParseIntPipe) id: number) {
    return this.invoicesService.findOne(id);
  }

  @UseGuards(RolesGuard)
  @Roles('SUPER_ADMIN', 'ADMIN', 'ACCOUNT_MANAGER', 'PROJECT_MANAGER', 'CONTRACTOR', 'VENDOR_CONTACT')
  @Post()
  create(@Body() dto: CreateInvoiceDto, @Req() req: any) {
    const isVendorUser = req.user.roles?.some((r: string) => ['CONTRACTOR', 'VENDOR_CONTACT'].includes(r));
    if (isVendorUser && dto.invoiceType === 'CLIENT') {
      throw new ForbiddenException('Vendor users cannot create client invoices');
    }
    return this.invoicesService.create(dto, req.user.id);
  }

  @Patch(':id')
  update(
    @Param('id', ParseIntPipe) id: number,
    @Body() dto: UpdateInvoiceDto,
    @Req() req: any,
  ) {
    return this.invoicesService.update(id, dto, req.user.id, req.user.roles);
  }

  @Delete(':id')
  remove(@Param('id', ParseIntPipe) id: number) {
    return this.invoicesService.remove(id);
  }

  // ── Workflow actions ─────────────────────────────────────────────────────────

  @Post(':id/submit')
  submit(@Param('id', ParseIntPipe) id: number, @Req() req: any) {
    return this.invoicesService.submit(id, req.user.id);
  }

  @Post(':id/approve')
  approve(@Param('id', ParseIntPipe) id: number, @Req() req: any) {
    return this.invoicesService.approve(id, req.user.id, req.user.roles ?? [], req.user.client?.id);
  }

  @Post(':id/reject')
  reject(
    @Param('id', ParseIntPipe) id: number,
    @Body('rejectionNote') rejectionNote: string,
    @Req() req: any,
  ) {
    return this.invoicesService.reject(id, req.user.id, rejectionNote, req.user.roles ?? []);
  }

  @Post(':id/request-revision')
  @UseGuards(RolesGuard)
  @Roles('SUPER_ADMIN', 'ADMIN', 'ACCOUNT_MANAGER', 'PROJECT_MANAGER')
  requestRevision(
    @Param('id', ParseIntPipe) id: number,
    @Body('revisionNote') revisionNote: string,
    @Req() req: any,
  ) {
    return this.invoicesService.requestRevision(id, req.user.id, revisionNote);
  }

  // ── Payments ─────────────────────────────────────────────────────────────────

  @Post(':id/payments')
  addPayment(
    @Param('id', ParseIntPipe) id: number,
    @Body() dto: CreatePaymentDto,
    @Req() req: any,
  ) {
    const { invoiceId: _ignored, ...payData } = dto;
    return this.invoicesService.addPayment(id, payData, req.user.id);
  }

  @Delete('payments/:paymentId')
  removePayment(@Param('paymentId', ParseIntPipe) paymentId: number) {
    return this.invoicesService.removePayment(paymentId);
  }
}
